### ISSUE TITLE
 Enable alpha blending => ALPHA_BLEND not found

### ISSUE THREAD

**Issue by marcgardent** [joshuaKnauber/layerpainter#1]
Hi,

context: version 1.1.2, Blender 2.8.0

The case : 
Add the first layer > Materials settings: 
* enable additional channels : Alpha
* Enable alpha blending : checked
> ok!

```
Info: LayerPainter activated!

Info: Layer reset!

Traceback (most recent call last):
  File "..\Blender Foundation\Blender\2.80\scripts\addons\layer_painter\operators\layer_ops.py", line 517, in execute
    self.set_channel_props()
  File "..\Blender Foundation\Blender\2.80\scripts\addons\layer_painter\operators\layer_ops.py", line 368, in set_channel_props
    self.enable_alpha_blending_mode()
  File "..\Blender Foundation\Blender\2.80\scripts\addons\layer_painter\operators\layer_ops.py", line 377, in enable_alpha_blending_mode
    material.blend_method = "ALPHA_BLEND"
TypeError: bpy_struct: item.attr = val: enum "ALPHA_BLEND" not found in ('OPAQUE', 'ADD', 'MULTIPLY', 'CLIP', 'HASHED', 'BLEND')
```

**Comment by joshuaKnauber** [comment]
Will be fixed in the next update, for now just enable Alpha Blend on your material manually.
